# Generated by Django 5.1.7 on 2025-03-25 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gestor_documentos', '0002_documento_datos_xml_documento_es_xml_asegurado_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='asegurado',
            name='archivo_xml',
            field=models.FileField(blank=True, null=True, upload_to='xmls/'),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='año1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='año2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='año3',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='año4',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='dia1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='dia2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='diagnostico',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='fecha_nacimiento',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='genero',
            field=models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('O', 'Otro')], default='O', max_length=1),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='id_asegurado',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='id_poliza',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='importe_factura1',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='iniciar_reclamo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='mes1',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='mes2',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='numero_factura1',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='rfc',
            field=models.CharField(blank=True, max_length=13, null=True),
        ),
        migrations.AddField(
            model_name='asegurado',
            name='titulat_conyuge_dependiente',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='asegurado',
            name='telefono',
            field=models.CharField(max_length=20),
        ),
    ]
