# Generated by Django 5.1.7 on 2025-03-24 14:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Comprobante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('folio', models.CharField(blank=True, max_length=50, null=True)),
                ('fecha', models.DateTimeField()),
                ('forma_pago', models.CharField(blank=True, max_length=10, null=True)),
                ('no_certificado', models.CharField(max_length=50)),
                ('certificado', models.TextField()),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=15)),
                ('moneda', models.CharField(blank=True, max_length=10, null=True)),
                ('exportacion', models.CharField(blank=True, max_length=10, null=True)),
                ('total', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_comprobante', models.CharField(blank=True, max_length=5, null=True)),
                ('metodo_pago', models.CharField(blank=True, max_length=10, null=True)),
                ('lugar_expedicion', models.CharField(blank=True, max_length=10, null=True)),
                ('sello', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='XMLFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='uploads/')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Complemento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.CharField(max_length=10)),
                ('uuid', models.CharField(max_length=50, unique=True)),
                ('fecha_timbrado', models.DateTimeField()),
                ('rfc_prov_certif', models.CharField(max_length=20)),
                ('sello_cfd', models.TextField()),
                ('no_certificado_sat', models.CharField(max_length=50)),
                ('sello_sat', models.TextField()),
                ('comprobante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='complemento', to='gestor_xml.comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Concepto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto_imp', models.CharField(blank=True, max_length=5, null=True)),
                ('clave_prod_serv', models.CharField(max_length=20)),
                ('no_identificacion', models.CharField(blank=True, max_length=50, null=True)),
                ('cantidad', models.DecimalField(decimal_places=2, max_digits=10)),
                ('clave_unidad', models.CharField(max_length=10)),
                ('unidad', models.CharField(blank=True, max_length=50, null=True)),
                ('descripcion', models.TextField()),
                ('valor_unitario', models.DecimalField(decimal_places=2, max_digits=15)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('comprobante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='conceptos', to='gestor_xml.comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Emisor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('regimen_fiscal', models.CharField(max_length=10)),
                ('comprobante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='emisor', to='gestor_xml.comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Impuestos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('total_trasladados', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('comprobante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='impuestos', to='gestor_xml.comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Receptor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfc', models.CharField(max_length=20)),
                ('nombre', models.CharField(max_length=200)),
                ('domicilio_fiscal', models.CharField(blank=True, max_length=10, null=True)),
                ('regimen_fiscal_receptor', models.CharField(max_length=10)),
                ('uso_cfdi', models.CharField(max_length=5)),
                ('comprobante', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='receptor', to='gestor_xml.comprobante')),
            ],
        ),
        migrations.CreateModel(
            name='Traslado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('impuesto', models.CharField(max_length=10)),
                ('base', models.DecimalField(decimal_places=2, max_digits=15)),
                ('tipo_factor', models.CharField(max_length=20)),
                ('tasa_o_cuota', models.DecimalField(decimal_places=6, max_digits=15)),
                ('importe', models.DecimalField(decimal_places=2, max_digits=15)),
                ('concepto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='traslados', to='gestor_xml.concepto')),
            ],
        ),
    ]
